export const COMMON_INSTITUTIONS = [
  // Universidades e Institutos Brasileiros
  "Universidade de São Paulo",
  "Universidade Estadual de Campinas",
  "Universidade Estadual Paulista",
  "Universidade Federal do Rio de Janeiro",
  "Universidade Federal de Minas Gerais",
  "Universidade Federal do Rio Grande do Sul",
  "Universidade Federal de Santa Catarina",
  "Universidade de Brasília",
  "Universidade Federal do Paraná",
  "Universidade Federal de Pernambuco",
  "Universidade Federal do Ceará",
  "Universidade Federal da Bahia",
  "Universidade Federal Fluminense",
  "Universidade Federal de São Carlos",
  "Universidade Federal de São Paulo",
  "Universidade do Estado do Rio de Janeiro",
  "Pontifícia Universidade Católica do Rio de Janeiro",
  "Pontifícia Universidade Católica do Rio Grande do Sul",
  "Pontifícia Universidade Católica de São Paulo",
  "Instituto Tecnológico de Aeronáutica",
  "Instituto Militar de Engenharia",
  "Fundação Oswaldo Cruz",
  "Centro Brasileiro de Pesquisas Físicas",
  "Instituto Nacional de Pesquisas Espaciais",
  
  // Universidades Internacionais
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "University of Cambridge",
  "University of Oxford",
  "California Institute of Technology",
  "Princeton University",
  "Yale University",
  "University of Chicago",
  "Columbia University",
  "Johns Hopkins University",
  "University of Pennsylvania",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "Cornell University",
  "University of Michigan",
  "University of Washington",
  "Duke University",
  "Northwestern University",
  "New York University",
  "Imperial College London",
  "UCL",
  "ETH Zurich",
  "Tsinghua University",
  "Peking University",
  "National University of Singapore",
  "University of Toronto",
  "McGill University",
  "University of Melbourne",
  "University of Sydney"
];
